PREFIX fx:  <http://sparql.xyz/facade-x/ns/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?stop ?parStation ?accName ?name WHERE {

  # stops
	SERVICE <x-sparql-anything:location=../result/datasets/%format/%size/STOPS.%format,%param,slice=%slice,strategy=%strategy,use-rdfs-member=true> {

    ?stopContainer rdfs:member [ a xyz:stop_id ; rdfs:member ?stop_id  ] .
    ?stopContainer rdfs:member [ a xyz:parent_station ; rdfs:member ?parent_station  ] .

    OPTIONAL {?stopContainer rdfs:member [ a xyz:stop_name ; rdfs:member ?accName  ] .} .

    ?stopContainer rdfs:member [ a xyz:location_type ; rdfs:member "2"  ] .

    ?stopContainerParStation rdfs:member [ a xyz:stop_name ; rdfs:member ?name ] .
    ?stopContainerParStation rdfs:member [ a xyz:stop_id ; rdfs:member ?parent_station  ] .

    BIND ( fx:entity( "http://transport.linkeddata.es/madrid/metro/stops/", ?stop_id ) AS ?stop ) .
    BIND ( fx:entity( "http://transport.linkeddata.es/madrid/metro/stops/", ?parent_station ) AS ?parStation ) .
	}

}
