ex -sc '1i|agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone,agency_fare_url' -cx AGENCY.csv
ex -sc '1i|service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date' -cx CALENDAR.csv
ex -sc '1i|service_id,date,exception_type' -cx CALENDAR_DATES.csv
ex -sc '1i|feed_publisher_name,feed_publisher_url,feed_lang,feed_start_date,feed_end_date,feed_version' -cx FEED_INFO.csv
ex -sc '1i|route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color' -cx ROUTES.csv
ex -sc '1i|trip_id,start_time,end_time,headway_secs,exact_times' -cx FREQUENCIES.csv
ex -sc '1i|shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled' -cx SHAPES.csv
ex -sc '1i|stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding' -cx STOPS.csv
ex -sc '1i|trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled' -cx STOP_TIMES.csv
ex -sc '1i|route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible' -cx TRIPS.csv
