FROM ubuntu:18.04

RUN apt-get update && apt-get install -y openjdk-8-jdk vim bc less wget unzip git

RUN mkdir -p engines/morph-rdb
COPY ["evaluate.sh", "engines"]
COPY morph-rdb engines/morph-rdb

RUN mkdir /results
RUN mkdir /data
RUN mkdir /mappings
RUN mkdir /queries


CMD ["tail", "-f", "/dev/null"]
