PREFIX fx:  <http://sparql.xyz/facade-x/ns/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
SELECT ?stop ?stopDescription ?wheelchairAccesible ?stopLat ?stopLon ?location  WHERE {
	SERVICE <x-sparql-anything:location=../result/datasets/%format/%size/STOPS.%format,%param,slice=%slice,strategy=%strategy> {

		?s xyz:stop_code ?stop_url .

		OPTIONAL { ?s xyz:stop_desc ?stopDescription . }
		
		OPTIONAL { 	?s xyz:wheelchair_boarding ?wheelchair_boarding .
					BIND ( fx:entity ( "http://transport.linkeddata.es/resource/WheelchairBoardingStatus/", ?wheelchair_boarding ) AS ?wheelchairAccesible ) 
		}
		
		OPTIONAL {
                ?s 	xyz:stop_lat ?stopLat .
    		    ?s	xyz:stop_lon ?stopLon .
    	}
		
		BIND ( fx:entity ( ?stop_url ) AS ?stop ) .
    	
    	?s xyz:location_type ?location_type  .
		
		BIND ( fx:entity ( "http://transport.linkeddata.es/resource/LocationType/", ?location_type ) AS ?location ) .
    	
    	FILTER (?location=<http://transport.linkeddata.es/resource/LocationType/2>)
	}
}
