PREFIX fx:  <http://sparql.xyz/facade-x/ns/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
SELECT (count(?route_url) as ?nRoutes) WHERE {
		SERVICE <x-sparql-anything:location=../result/datasets/%format/%size/ROUTES.%format,%param,slice=%slice,strategy=%strategy> {
			?r xyz:route_url ?route_url .
			?r xyz:agency_id ?agency_id.
			FILTER (?agency_id="00000000000000000005")
		}
}
